name: Setup and Run GMod Server

on: [push]

jobs:
  setup-gmod-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      
      - name: Install GMod Server
        run: steamcmd +login anonymous +app_update 4020 validate +quit

      - name: Configure server
        run: |
          # Place your server configuration files here, or modify them as needed.
          # For example, copy a preconfigured server.cfg file:
          # cp path/to/server.cfg ~/gmod_server/garrysmod/cfg/

      - name: Start GMod Server
        run: |
          cd ~/gmod_server
          ./srcds_run -game garrysmod +maxplayers 16 +map gm_construct
