name: Setup and run the CityRP2 server

on: [push]

jobs:
  setup-gmod-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: setup-steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      
      - name: Install GMod Server
        run: steamcmd +login anonymous +app_update 4020 validate +quit

      - name: Go to the gmod server directory
        run: cd ${{ steps.setup-steamcmd.outputs.directory }}

      - name: Ls the directory
        run: ls steamcmd/linux32

      - name: Find files matching "*.rs" or "*.md"
        uses: jeertmans/filesfinder@latest
        id: ff # Any id, to be used later to reference to files output
        with:
            # Only argument, a single string, to be passed as arguments to ff.
            # See `ff --help` for more help.
            # Default: "*"
            args: "srcds_run"
      - name: Print files
        run: echo "${{ steps.ff.outputs.files }}"

      - name: Find srcds_run
        run: find / -iname 'srcds_run'

      - name: Find srcds_run
        run: locate -i srcds_run

#      - name: Configure server
#        run: |
#          # Place your server configuration files here, or modify them as needed.
#          # For example, copy a preconfigured server.cfg file:
#          # cp path/to/server.cfg ~/gmod_server/garrysmod/cfg/
#
#      - name: Start GMod Server
#        run: |
#          cd ~/gmod_server
#          ./srcds_run -game garrysmod +maxplayers 16 +map gm_construct
