name: Setup and run the CityRP2 server

on: [push]

jobs:
  setup-gmod-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: setup-steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      
      - name: Install GMod Server
        run: steamcmd +login anonymous +app_update 4020 validate +quit

      - name: Go to the gmod server directory
        run: cd ${{ steps.setup-steamcmd.outputs.directory }}

      - name: Ls the directory
        run: ls steamcmd/linux32

      - name: cd Steam
        run: |
            cd ~/Steam/steamapps/common/GarrysModDS
            ./srcds_run -game garrysmod +maxplayers 16 +map gm_construct +gamemode sandbox

      - name: lsss
        run: ls

      - name: Find srcds_run
        run: find / -iname 'srcds_run'

      - name: Find srcds_run
        run: locate -i srcds_run

      - name: cd steam
        run: cd ~/.steam

#      - name: Configure server
#        run: |
#          # Place your server configuration files here, or modify them as needed.
#          # For example, copy a preconfigured server.cfg file:
#          # cp path/to/server.cfg ~/gmod_server/garrysmod/cfg/
#
#      - name: Start GMod Server
#        run: |
#          cd ~/gmod_server
#          ./srcds_run -game garrysmod +maxplayers 16 +map gm_construct
